anguage: java
jdk:
  - oraclejdk8
  - openjdk11
sudo: true
dist: precise
install: /bin/true
notifications:
  email:
    - github-awsforjava@amazon.com
script: mvn install -Dmaven.test.skip=true

after_success:
    - bash <(curl -s https://codecov.io/bash) -F unittests
